---
'':
  - ttl: 1800
    type: A
    value: 65.21.116.72
  - ttl: 1800
    type: CAA
    values:
      - flags: 0
        tag: iodef
        value: mailto:mtrnord@nordgedanken.dev
      - flags: 0
        tag: issue
        value: letsencrypt.org; validationmethods=tls-alpn-01,dns-01,http-01
  - ttl: 1800
    type: MX
    value:
      exchange: mail.midnightthoughts.space.
      preference: 10
  - ttl: 600
    type: NS
    values:
      - ns1.nordgedanken.dev.
      - ns2.nordgedanken.dev.
      - ns3.nordgedanken.dev.
  - ttl: 1800
    type: TXT
    value: google-site-verification=YeO0rqvYWOZoW6yj3MRf77luDe9CURDbmPYLFYiBXo8
_acme-challenge:
  ttl: 120
  type: TXT
  value: cMQRSxgQAHLT5soPEADoNdXpT3FoiA2j3O404y4s85Q
_dmarc.mail:
  ttl: 1800
  type: TXT
  value: v=DMARC1\; p=none\; sp=none\; fo=1\; ri=3600\; rua=mailto:mtrnord@nordgedanken.dev\;
    ruf=mailto:mtrnord@nordgedanken.dev
art:
  ttl: 1800
  type: A
  value: 65.21.116.72
coreharbor.kubernetes:
  ttl: 1800
  type: A
  value: 65.21.116.72
dashboard.kubernetes:
  ttl: 1800
  type: A
  value: 65.21.116.72
default._domainkey.mail:
  ttl: 1800
  type: TXT
  value: v=DKIM1\; k=rsa\; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCa+VrLSqHv7jEXdYtE8L+ZnwgMW9o8mV+kKGdl1emUNLe4TcOOUG8rU3zqU8VM8vnBjYAKLLrY6Exq7nqkLMXmTf9pmD3Y5LY4PVbZucDVfD4wFmtn0mSaUkZW2G8F9oJ3CvQqU94JbYCiXB+l9mkTiZloKOoKdFrjxBBOeSMD3QIDAQAB
docs.draupnir:
  ttl: 1800
  type: CNAME
  value: the-draupnir-project.github.io.
draupnir:
  ttl: 1800
  type: A
  value: 65.21.116.72
fleet:
  ttl: 1800
  type: A
  value: 65.21.116.72
grafana:
  ttl: 1800
  type: A
  value: 65.21.116.72
headscale:
  - ttl: 1800
    type: A
    value: 49.13.24.105
  - ttl: 1800
    type: AAAA
    value: 2a01:4f8:c012:492::1
hookshot:
  ttl: 1800
  type: A
  value: 65.21.116.72
keycloak:
  ttl: 1800
  type: A
  value: 65.21.116.72
kubernetes:
  - ttl: 1800
    type: A
    value: 95.217.202.35
  - ttl: 1800
    type: AAAA
    value: 2a01:4f9:4a:451c:2::5
lg:
  - ttl: 1800
    type: A
    value: 49.13.24.105
  - ttl: 1800
    type: AAAA
    value: 2a01:4f8:c012:492::1
mail:
  - ttl: 1800
    type: A
    value: 95.217.202.35
  - ttl: 1800
    type: AAAA
    value: 2a01:4f9:4a:451c:ffff:ffff:ffff:eeee
  - ttl: 1800
    type: MX
    value:
      exchange: mail.midnightthoughts.space.
      preference: 10
  - ttl: 1800
    type: TXT
    values:
      - google-site-verification=d5k_X67W_dLDw_KMEqTywt6s3ywb_3Nh-dWUuhoAhz0
      - v=spf1 mx include:_spf.mx.cloudflare.net a:mail.midnightthoughts.space ip4:65.21.116.72
        ~all
matrix:
  ttl: 1800
  type: A
  value: 65.21.116.72
matrix.art:
  ttl: 1800
  type: A
  value: 65.21.116.72
matrix.draupnir:
  ttl: 1800
  type: A
  value: 65.21.116.72
nordgedanken.lg:
  ttl: 1800
  type: A
  value: 10.100.0.2
notes:
  ttl: 1800
  type: CNAME
  value: cname.vercel-dns.com.
pbx:
  - ttl: 1800
    type: A
    value: 49.13.24.105
  - ttl: 1800
    type: AAAA
    value: 2a01:4f8:c012:492::1
postgres-ui:
  ttl: 1800
  type: A
  value: 65.21.116.72
postgres.internal:
  ttl: 1800
  type: A
  value: 10.100.12.1
redmine:
  ttl: 1800
  type: A
  value: 65.21.116.72
rspamd:
  - ttl: 1800
    type: A
    value: 65.21.116.74
  - ttl: 1800
    type: AAAA
    value: 2a01:4f9:4a:451c:2::2
search.art:
  ttl: 1800
  type: A
  value: 65.21.116.72
sliding.matrix:
  ttl: 1800
  type: A
  value: 65.21.116.72
spec:
  ttl: 1800
  type: A
  value: 65.21.116.72
status.draupnir:
  ttl: 1800
  type: CNAME
  value: the-draupnir-project.github.io.
weave:
  ttl: 1800
  type: A
  value: 65.21.116.72
webhook.kubernetes:
  ttl: 1800
  type: A
  value: 65.21.116.72
worker-1.lg:
  ttl: 1800
  type: A
  value: 10.100.0.1
worker-2.lg:
  ttl: 1800
  type: A
  value: 10.100.0.3
zammad:
  ttl: 1800
  type: A
  value: 65.21.116.72
znc:
  - ttl: 1800
    type: A
    value: 49.13.24.105
  - ttl: 1800
    type: AAAA
    value: 2a01:4f8:c012:492::1
# Personal discourse store
personal:
  - ttl: 1800
    type: A
    value: 37.27.5.79
  - ttl: 1800
    type: AAAA
    value: "2a01:4f9:c012:54d3::"

