---
'':
  - ttl: 1800
    type: A
    values:
      # - 65.21.116.72
      #- 159.69.103.159
      #- 65.109.241.200
      - 95.217.31.57
  - ttl: 60
    type: AAAA
    values:
      #- '2a01:4f8:c012:492::1'
      #- '2a01:4f9:c012:54d3::1'
      - '2a01:4f9:c010:9436::2'
  - ttl: 1800
    type: CAA
    values:
      - flags: 0
        tag: iodef
        value: mailto:mtrnord@nordgedanken.dev
      - flags: 0
        tag: issue
        value: letsencrypt.org; validationmethods=tls-alpn-01,dns-01,http-01
  - ttl: 1800
    type: MX
    value:
      exchange: mail.midnightthoughts.space.
      preference: 10
  - ttl: 1800
    type: TXT
    value: google-site-verification=YeO0rqvYWOZoW6yj3MRf77luDe9CURDbmPYLFYiBXo8
_dmarc.mail:
  ttl: 1800
  type: TXT
  value: v=DMARC1\; p=none\; sp=none\; fo=1\; ri=3600\; rua=mailto:mtrnord@nordgedanken.dev\;
    ruf=mailto:mtrnord@nordgedanken.dev
default._domainkey.mail:
  ttl: 1800
  type: TXT
  value: v=DKIM1\; k=rsa\; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCa+VrLSqHv7jEXdYtE8L+ZnwgMW9o8mV+kKGdl1emUNLe4TcOOUG8rU3zqU8VM8vnBjYAKLLrY6Exq7nqkLMXmTf9pmD3Y5LY4PVbZucDVfD4wFmtn0mSaUkZW2G8F9oJ3CvQqU94JbYCiXB+l9mkTiZloKOoKdFrjxBBOeSMD3QIDAQAB
docs.draupnir:
  ttl: 1800
  type: CNAME
  value: the-draupnir-project.github.io.
headscale:
  - ttl: 1800
    type: A
    value: 49.13.24.105
kubernetes:
  - ttl: 1800
    type: A
    value: 95.217.202.35
#  - ttl: 1800
#    type: AAAA
#    value: 2a01:4f9:4a:451c:2::5
lg:
  - ttl: 1800
    type: A
    value: 49.13.24.105
mail:
  - ttl: 1800
    type: A
    value: 95.217.202.35
  - ttl: 1800
    type: AAAA
    value: 2a01:4f9:4a:451c:ffff:ffff:ffff:eeee
  - ttl: 1800
    type: MX
    value:
      exchange: mail.midnightthoughts.space.
      preference: 10
  - ttl: 1800
    type: TXT
    values:
      - google-site-verification=d5k_X67W_dLDw_KMEqTywt6s3ywb_3Nh-dWUuhoAhz0
      - v=spf1 mx include:_spf.mx.cloudflare.net a:mail.midnightthoughts.space ip4:65.21.116.72
        ~all
kubernetes_ingress: &kubernetes
  - ttl: 60
    type: A
    values:
      #- 65.21.116.72
      #- 159.69.103.159
      #- 65.109.241.200
      - 95.217.31.57
  - ttl: 60
    type: AAAA
    values:
      #- '2a01:4f8:c012:492::1'
      #- '2a01:4f9:c012:54d3::1'
      - '2a01:4f9:c010:9436::2'
sliding.matrix: *kubernetes
weave: *kubernetes
webhook.kubernetes: *kubernetes
zammad: *kubernetes
fleet: *kubernetes
hookshot: *kubernetes
keycloak: *kubernetes
users: *kubernetes
admin.users: *kubernetes

vault: &new_cluster
  - type: A
    value: 95.217.170.156
  - type: AAAA
    value: '2a01:4f9:c01e:32d::1'
matrix.draupnir: *new_cluster
grafana: *new_cluster
ui.k8s: *new_cluster
matrix: *new_cluster
dashboard.kubernetes: *new_cluster
auth: *new_cluster

nordgedanken.lg:
  ttl: 1800
  type: A
  value: 10.0.1.2
notes:
  ttl: 1800
  type: CNAME
  value: cname.vercel-dns.com.
pbx:
  - ttl: 1800
    type: A
    value: 49.13.24.105
postgres.internal:
  ttl: 60
  type: A
  value: 10.0.3.1
redmine: *kubernetes
rspamd:
  - ttl: 1800
    type: A
    value: 65.21.116.74
  - ttl: 1800
    type: AAAA
    value: 2a01:4f9:4a:451c:2::2
status.draupnir:
  ttl: 1800
  type: CNAME
  value: the-draupnir-project.github.io.
worker-1.lg:
  ttl: 1800
  type: A
  value: 10.0.2.3
worker-2.lg:
  ttl: 1800
  type: A
  value: 10.0.2.2
znc:
  - ttl: 1800
    type: A
    value: 49.13.24.105
soju:
  - ttl: 1800
    type: A
    value: 37.27.5.79
search:
  - ttl: 1800
    type: A
    value: "37.27.5.79"
  - ttl: 1800
    type: AAAA
    value: "2a01:4f9:c012:54d3::"
# Personal discourse store
personal:
  - ttl: 1800
    type: A
    value: 37.27.5.79
  - ttl: 1800
    type: AAAA
    value: "2a01:4f9:c012:54d3::"

_acme-challenge:
  ttl: 15
  type: TXT
  value: Mb0--1OsXaW3G2ugkX8VmsVBJ2ijCg8gf301rxfqK0E
