---
'':
  - ttl: 1800
    type: A
    value: 65.21.116.72
  - ttl: 1800
    type: CAA
    values:
      - flags: 0
        tag: iodef
        value: mailto:mtrnord@nordgedanken.dev
      - flags: 0
        tag: issue
        value: letsencrypt.org; validationmethods=tls-alpn-01,dns-01,http-01
  - ttl: 1800
    type: MX
    value:
      exchange: mail.midnightthoughts.space.
      preference: 10
  - ttl: 600
    type: NS
    values:
      - ns1.nordgedanken.dev.
      - ns2.nordgedanken.dev.
      - ns3.nordgedanken.dev.
  - ttl: 1800
    type: TXT
    value: google-site-verification=YeO0rqvYWOZoW6yj3MRf77luDe9CURDbmPYLFYiBXo8
_acme-challenge:
  ttl: 120
  type: TXT
  value: JCNdV9ZjnlmosmLQQHncPLOYCRikQoi0I6MPzrnzLwA
_dmarc.mail:
  ttl: 1800
  type: TXT
  value: v=DMARC1\; p=none\; sp=none\; fo=1\; ri=3600\; rua=mailto:mtrnord@nordgedanken.dev\;
    ruf=mailto:mtrnord@nordgedanken.dev
default._domainkey.mail:
  ttl: 1800
  type: TXT
  value: v=DKIM1\; k=rsa\; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCa+VrLSqHv7jEXdYtE8L+ZnwgMW9o8mV+kKGdl1emUNLe4TcOOUG8rU3zqU8VM8vnBjYAKLLrY6Exq7nqkLMXmTf9pmD3Y5LY4PVbZucDVfD4wFmtn0mSaUkZW2G8F9oJ3CvQqU94JbYCiXB+l9mkTiZloKOoKdFrjxBBOeSMD3QIDAQAB
docs.draupnir:
  ttl: 1800
  type: CNAME
  value: the-draupnir-project.github.io.
headscale:
  - ttl: 1800
    type: A
    value: 49.13.24.105
  - ttl: 1800
    type: AAAA
    value: 2a01:4f8:c012:492::1
kubernetes:
  - ttl: 1800
    type: A
    value: 95.217.202.35
  - ttl: 1800
    type: AAAA
    value: 2a01:4f9:4a:451c:2::5
lg:
  - ttl: 1800
    type: A
    value: 49.13.24.105
  - ttl: 1800
    type: AAAA
    value: 2a01:4f8:c012:492::1
mail:
  - ttl: 1800
    type: A
    value: 95.217.202.35
  - ttl: 1800
    type: AAAA
    value: 2a01:4f9:4a:451c:ffff:ffff:ffff:eeee
  - ttl: 1800
    type: MX
    value:
      exchange: mail.midnightthoughts.space.
      preference: 10
  - ttl: 1800
    type: TXT
    values:
      - google-site-verification=d5k_X67W_dLDw_KMEqTywt6s3ywb_3Nh-dWUuhoAhz0
      - v=spf1 mx include:_spf.mx.cloudflare.net a:mail.midnightthoughts.space ip4:65.21.116.72
        ~all
        
kubernetes_ingress: &kubernetes
  - ttl: 60
    type: A
    values:
      - 65.21.116.72
  - ttl: 60
    type: AAAA
    value: '2a01:4f9:4a:451c::1'
matrix: *kubernetes
matrix.art: *kubernetes
matrix.draupnir: *kubernetes
postgres-ui: *kubernetes
search.art: *kubernetes
sliding.matrix: *kubernetes
spec: *kubernetes
weave: *kubernetes
webhook.kubernetes: *kubernetes
zammad: *kubernetes
art: *kubernetes
coreharbor.kubernetes: *kubernetes
dashboard.kubernetes: *kubernetes
draupnir: *kubernetes
fleet: *kubernetes
grafana: *kubernetes
hookshot: *kubernetes
keycloak: *kubernetes

nordgedanken.lg:
  ttl: 1800
  type: A
  value: 10.100.0.2
notes:
  ttl: 1800
  type: CNAME
  value: cname.vercel-dns.com.
pbx:
  - ttl: 1800
    type: A
    value: 49.13.24.105
  - ttl: 1800
    type: AAAA
    value: 2a01:4f8:c012:492::1
postgres.internal:
  ttl: 1800
  type: A
  value: 10.100.12.1
redmine: *kubernetes
rspamd:
  - ttl: 1800
    type: A
    value: 65.21.116.74
  - ttl: 1800
    type: AAAA
    value: 2a01:4f9:4a:451c:2::2
status.draupnir:
  ttl: 1800
  type: CNAME
  value: the-draupnir-project.github.io.
worker-1.lg:
  ttl: 1800
  type: A
  value: 10.100.0.1
worker-2.lg:
  ttl: 1800
  type: A
  value: 10.100.0.3
znc:
  - ttl: 1800
    type: A
    value: 49.13.24.105
  - ttl: 1800
    type: AAAA
    value: 2a01:4f8:c012:492::1
search:
  - ttl: 1800
    type: A
    value: "37.27.5.79"
  - ttl: 1800
    type: AAAA
    value: "2a01:4f9:c012:54d3::"
# Personal discourse store
personal:
  - ttl: 1800
    type: A
    value: 37.27.5.79
  - ttl: 1800
    type: AAAA
    value: "2a01:4f9:c012:54d3::"

