---
'':
  - ttl: 1800
    type: A
    value: 65.21.116.72
  - ttl: 1800
    type: CAA
    values:
      - flags: 0
        tag: iodef
        value: mailto:mtrnord@nordgedanken.dev
      - flags: 0
        tag: issue
        value: letsencrypt.org; validationmethods=tls-alpn-01,dns-01,http-01
  - ttl: 1800
    type: MX
    value:
      exchange: mail.nordgedanken.dev.
      preference: 10
  - ttl: 600
    type: NS
    values:
      - ns1.nordgedanken.dev.
      - ns2.nordgedanken.dev.
      - ns3.nordgedanken.dev.
  - ttl: 1800
    type: TXT
    value: google-site-verification=tcGRl_gNRBdFRI8-tNAPj6x-8FbmGihFNcYn9_xS7tc
data:
  ttl: 1800
  type: A
  value: 65.21.116.72
en:
  ttl: 1800
  type: A
  value: 65.21.116.72
forum:
  ttl: 1800
  type: A
  value: 49.13.24.105
