---
'':
  - ttl: 1800
    type: A
    value: "65.21.116.74"
  - ttl: 1800
    type: AAAA
    value: "2a01:4f9:4a:451c:2::5"
  - ttl: 1800
    type: CAA
    values:
      - flags: 0
        tag: iodef
        value: mailto:mtrnord@nordgedanken.dev
      - flags: 0
        tag: issue
        value: letsencrypt.org; validationmethods=tls-alpn-01,dns-01,http-01
  - ttl: 1800
    type: MX
    values:
      - exchange: in1-smtp.messagingengine.com.
        preference: 10
      - exchange: in2-smtp.messagingengine.com.
        preference: 20
  - ttl: 1800
    type: TXT
    values:
      - google-site-verification=SkIjIdwvyBPvaivZFa5KgLX22pwSJdINdaTf0XAi5Qc
      - v=spf1 include:spf.messagingengine.com ?all
'*':
  ttl: 1800
  type: MX
  values:
    - exchange: in1-smtp.messagingengine.com.
      preference: 10
    - exchange: in2-smtp.messagingengine.com.
      preference: 20

_submission._tcp:
  type: SRV
  value:
    port: 587
    priority: 0
    target: smtp.fastmail.com.
    weight: 1
_imap._tcp:
  type: SRV
  value:
    port: 0
    priority: 0
    target: .
    weight: 0
_imaps._tcp:
  type: SRV
  value:
    port: 993
    priority: 0
    target: imap.fastmail.com.
    weight: 1
_pop3._tcp:
  type: SRV
  value:
    port: 0
    priority: 0
    target: .
    weight: 0
_pop3s._tcp:
  type: SRV
  value:
    port: 995
    priority: 10
    target: pop.fastmail.com.
    weight: 1
_jmap._tcp:
  type: SRV
  value:
    port: 443
    priority: 0
    target: api.fastmail.com.
    weight: 1
_autodiscover._tcp:
  type: SRV
  value:
    port: 443
    priority: 0
    target: autodiscover.fastmail.com.
    weight: 1
_carddav._tcp:
  type: SRV
  value:
    port: 0
    priority: 0
    target: .
    weight: 0
_carddavs._tcp:
  type: SRV
  value:
    port: 443
    priority: 0
    target: carddav.fastmail.com.
    weight: 1
_caldav._tcp:
  type: SRV
  value:
    port: 0
    priority: 0
    target: .
    weight: 0
_caldavs._tcp:
  type: SRV
  value:
    port: 443
    priority: 0
    target: caldav.fastmail.com.
    weight: 1
_dmarc:
  type: TXT
  value: v=DMARC1\; p=none

fm1._domainkey:
  type: CNAME
  value: fm1.nordgedanken.dev.dkim.fmhosted.com.

fm2._domainkey:
  type: CNAME
  value: fm2.nordgedanken.dev.dkim.fmhosted.com.

fm3._domainkey:
  type: CNAME
  value: fm3.nordgedanken.dev.dkim.fmhosted.com.

# Family
recipes:
  type: CNAME
  value: mtrnord.github.io.

# Kubernetes
kubernetes: &kubernetes
  - ttl: 60
    type: A
    values:
      #- 65.21.116.72
      #- 159.69.103.159
      #- 65.109.241.200
      - 95.217.31.57
  - ttl: 60
    type: AAAA
    values:
      #- '2a01:4f8:c012:492::1'
      #- '2a01:4f9:c012:54d3::1'
      - '2a01:4f9:c010:9436::2'
auth: *kubernetes
git: *kubernetes
github-hook: *kubernetes
netbox: *kubernetes
paperless: *kubernetes
search: *kubernetes
zuul: *kubernetes
piwigo: *kubernetes
umami: *kubernetes
chaos: *kubernetes

# Others
mastodon:
  - ttl: 1800
    type: A
    value: 37.27.5.79
  - ttl: 1800
    type: AAAA
    value: '2a01:4f9:c012:54d3::'

# Local Homenet
local:
  - ttl: 60
    type: A
    value: 95.217.157.108
  - ttl: 60
    type: AAAA
    value: 2a01:4f9:c010:9436::1

_acme-challenge:
  ttl: 15
  type: TXT
  value: NuK9J23OlRSzjLcGG4XYvecym6YhFCcgLtZdLCCnaVA
