---
name: Force deploy
on:
  workflow_dispatch:
  repository_dispatch:
    types: [force-deploy-command]
jobs:
  force_deploy:
    permissions:
      issues: write
      pull-requests: write
      contents: read
      statuses: write
    runs-on: ubuntu-latest
    if: github.event.client_payload.pull_request
    steps:
      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          status: pending
          context: Force deploying changes
          sha: ${{ github.event.client_payload.pull_request.head.sha }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - uses: solvaholic/octodns-sync@main
        with:
          config_path: config/production.yaml
          force: "Yes"
          doit: --doit
        env:
          POWERDNS_API_KEY_NS1: ${{ secrets.POWERDNS_API_KEY_NS1 }}
          POWERDNS_API_KEY_NS2: ${{ secrets.POWERDNS_API_KEY_NS2 }}
          POWERDNS_API_KEY_NS3: ${{ secrets.POWERDNS_API_KEY_NS3 }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ github.event.client_payload.pull_request.head.sha }}
          status: ${{ job.status }}
          context: Force deploying changes
