---
name: Validate
on:
  push:
    branches: [main]
  repository_dispatch:
    types: [validate-command]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch
        if: github.event.client_payload.slash_command
      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          status: pending
          context: Linting changes
          sha: ${{ steps.comment-branch.outputs.head_sha }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run yamllint
        run: yamllint .
      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@master
        if: github.event.client_payload.slash_command
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          status: ${{ job.status }}
          context: Linting changes

  validate:
    permissions:
      issues: write
      pull-requests: write
      contents: read
      statuses: write
    needs: linting
    if: github.event.client_payload.slash_command
    runs-on: ubuntu-latest
    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch
      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          status: pending
          context: Verifying changes
          sha: ${{ steps.comment-branch.outputs.head_sha }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - uses: solvaholic/octodns-sync@main
        with:
          config_path: config/production.yaml
          force: "Yes"
        env:
          POWERDNS_API_KEY_NS1: ${{ secrets.POWERDNS_API_KEY_NS1 }}
          POWERDNS_API_KEY_NS2: ${{ secrets.POWERDNS_API_KEY_NS2 }}
          POWERDNS_API_KEY_NS3: ${{ secrets.POWERDNS_API_KEY_NS3 }}
      - name: Get plan output
        id: meta
        run: |
          # Parse plan output into $_plan
          _plan="$(cat ${GITHUB_WORKSPACE}/octodns-sync.plan)"
          _plan="${_plan//'%'/'%25'}"
          _plan="${_plan//$'\n'/'%0A'}"
          _plan="${_plan//$'\r'/'%0D'}"
          # Set output 'plan' to $_plan
          echo "::set-output name=plan::${_plan}"
          # Set $_sha to the first 7 char of PR head SHA
          _sha="$(echo "${{ steps.comment-branch.outputs.head_sha }}" | cut -c 1-7)"
          # Set output 'sha' to $_sha
          echo "::set-output name=sha::${_sha}"
      - name: Find comment
        uses: peter-evans/find-comment@v2.4.0
        id: fc
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-author: github-actions[bot]
          body-includes: Automatically generated by octodns-sync
      - name: Add or update PR comment
        uses: peter-evans/create-or-update-comment@v3.0.2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            ## OctoDNS Plan for `${{ steps.meta.outputs.sha }}`
            ${{ steps.meta.outputs.plan }}
            Automatically generated by octodns-sync
          edit-mode: replace

      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          status: ${{ job.status }}
          context: Verifying changes
